import {defineCatalog} from "./helpers.js";

const LAPTOP="https://www.akakce.com/laptop-notebook.html";
const DESKTOP="https://www.akakce.com/bilgisayar-masaustu.html";

const definitions=[
  {deviceType:"dizustu-bilgisayar",brand:"apple",familySlug:"macbook-air",familyName:"MacBook Air",familyKind:"official-family",marketSourceUrl:LAPTOP,catalogBasis:"Akakçe pazar keşfi + Apple Türkiye Mac ürün ve destek sayfaları",productUrl:"https://www.apple.com/tr/macbook-air/",supportUrl:"https://support.apple.com/tr-tr/macbook-air",manualUrl:"https://support.apple.com/tr-tr/guide/macbook-air/welcome/mac",softwareUrl:"https://support.apple.com/tr-tr/macos",softwareLabel:"Apple macOS güncelleme ve destek",models:[{name:"MacBook Air 13 inç (M2)",code:"MacBook Air M2 13"},{name:"MacBook Air 13 inç (M4)",code:"MacBook Air M4 13"},{name:"MacBook Air 15 inç (M4)",code:"MacBook Air M4 15"},{name:"MacBook Air 13 inç (M5)",code:"MacBook Air M5 13"},{name:"MacBook Air 15 inç (M5)",code:"MacBook Air M5 15"}]},
  {deviceType:"dizustu-bilgisayar",brand:"apple",familySlug:"macbook-pro",familyName:"MacBook Pro",familyKind:"official-family",marketSourceUrl:LAPTOP,catalogBasis:"Akakçe pazar keşfi + Apple Türkiye Mac ürün ve destek sayfaları",productUrl:"https://www.apple.com/tr/macbook-pro/",supportUrl:"https://support.apple.com/tr-tr/macbook-pro",manualUrl:"https://support.apple.com/tr-tr/guide/macbook-pro/welcome/mac",softwareUrl:"https://support.apple.com/tr-tr/macos",softwareLabel:"Apple macOS güncelleme ve destek",models:[{name:"MacBook Pro 14 inç (M4 Pro)",code:"MacBook Pro M4 Pro 14"},{name:"MacBook Pro 14 inç (M5)",code:"MacBook Pro M5 14"},{name:"MacBook Pro 14 inç (M5 Pro)",code:"MacBook Pro M5 Pro 14"},{name:"MacBook Pro 16 inç (M5 Pro)",code:"MacBook Pro M5 Pro 16"},{name:"MacBook Pro 14 inç (M5 Max)",code:"MacBook Pro M5 Max 14"}]},
  {deviceType:"dizustu-bilgisayar",brand:"lenovo",familySlug:"dizustu-modelleri",familyName:"Dizüstü Bilgisayar Modelleri",marketSourceUrl:LAPTOP,catalogBasis:"Akakçe pazar keşfi + Lenovo Türkiye ürün ve seri/model destek portalı",productUrl:"https://www.lenovo.com/tr/tr/laptops/",supportUrl:"https://support.lenovo.com/tr/tr/",manualUrl:"https://support.lenovo.com/tr/tr/",softwareUrl:"https://support.lenovo.com/tr/tr/",models:[{name:"ThinkBook 16p Gen 6 ADR 21U00013TX",code:"21U00013TX"},{name:"IdeaPad Slim 3 15IRH10 83K1003MTR",code:"83K1003MTR"},{name:"IdeaPad Slim 3 15IRH10 83K10016TR",code:"83K10016TR"},{name:"Yoga Slim 7 14IMH9 83CV00E4TR",code:"83CV00E4TR"},{name:"V14 Gen 4 AMN 82YT00JHTX",code:"82YT00JHTX"},{name:"IdeaPad Slim 3 14ARP10 83K6006JTR",code:"83K6006JTR"}]},
  {deviceType:"dizustu-bilgisayar",brand:"asus",familySlug:"dizustu-modelleri",familyName:"Dizüstü Bilgisayar Modelleri",marketSourceUrl:LAPTOP,catalogBasis:"Akakçe pazar keşfi + ASUS Türkiye ürün/destek merkezi",productUrl:"https://www.asus.com/tr/laptops/for-home/all-series/",supportUrl:"https://www.asus.com/tr/support/",manualUrl:"https://www.asus.com/tr/support/download-center/",softwareUrl:"https://www.asus.com/tr/support/download-center/",models:[{name:"Zenbook 14 UX3402VA-KP659W",code:"UX3402VA-KP659W"},{name:"Vivobook 15 X1504VA-BQ3970W",code:"X1504VA-BQ3970W"},{name:"Vivobook 16 V3607VU-RP061W",code:"V3607VU-RP061W"},{name:"ProArt P16 H7606WP-SR312",code:"H7606WP-SR312"}]},
  {deviceType:"dizustu-bilgisayar",brand:"casper",familySlug:"nirvana",familyName:"Nirvana",familyKind:"official-family",marketSourceUrl:LAPTOP,catalogBasis:"Akakçe pazar keşfi + Casper Türkiye ürün/destek",productUrl:"https://www.casper.com.tr/laptop-bilgisayar",supportUrl:"https://www.casper.com.tr/destek",manualUrl:"https://www.casper.com.tr/destek",softwareUrl:"https://www.casper.com.tr/destek",models:[{name:"Nirvana S100.1362-DF00X-G-F",code:"S100.1362-DF00X-G-F"},{name:"Nirvana S100.255H-DF00X-G-F",code:"S100.255H-DF00X-G-F"},{name:"Nirvana S100.255H-BV00X-G-F",code:"S100.255H-BV00X-G-F"},{name:"Nirvana X650.1342-DV00X-G-F",code:"X650.1342-DV00X-G-F"},{name:"Nirvana S200.1342-CX00X-G-F",code:"S200.1342-CX00X-G-F"},{name:"Nirvana X650.1342-BV00X-G-F",code:"X650.1342-BV00X-G-F"}]},
  {deviceType:"dizustu-bilgisayar",brand:"huawei",familySlug:"matebook",familyName:"MateBook",familyKind:"official-family",marketSourceUrl:LAPTOP,catalogBasis:"Akakçe pazar keşfi + Huawei Türkiye dizüstü ürün/destek",productUrl:"https://consumer.huawei.com/tr/laptops/",supportUrl:"https://consumer.huawei.com/tr/support/",manualUrl:"https://consumer.huawei.com/tr/support/",softwareUrl:"https://consumer.huawei.com/tr/support/pc-manager/",models:["MateBook 14 2024","MateBook D 16 2024","MateBook D 16 (13. Nesil Intel)"]},
  {deviceType:"dizustu-bilgisayar",brand:"acer",familySlug:"dizustu-modelleri",familyName:"Dizüstü Bilgisayar Modelleri",marketSourceUrl:LAPTOP,catalogBasis:"Akakçe pazar keşfi + Acer Türkiye ürün/destek",productUrl:"https://www.acer.com/tr-tr/laptops",supportUrl:"https://www.acer.com/tr-tr/support/index.html",manualUrl:"https://www.acer.com/tr-tr/support/drivers-and-manuals",softwareUrl:"https://www.acer.com/tr-tr/support/drivers-and-manuals",models:[{name:"Aspire Lite AL16-54P-59GP",code:"NX.D76EY.001"},{name:"Aspire 3 A315-59",code:"A315-59"},{name:"Swift Go 14 SFG14",code:"SFG14"}]},
  {deviceType:"dizustu-bilgisayar",brand:"hp",familySlug:"dizustu-modelleri",familyName:"Dizüstü Bilgisayar Modelleri",marketSourceUrl:LAPTOP,catalogBasis:"Akakçe pazar keşfi + HP Türkiye seri/model destek portalı",productUrl:"https://www.hp.com/tr-tr/shop/list.aspx?fc_ptyp_laptops=1",supportUrl:"https://support.hp.com/tr-tr/",manualUrl:"https://support.hp.com/tr-tr/",softwareUrl:"https://support.hp.com/tr-tr/drivers",models:[{name:"HP 15-fd2026nt",code:"D51E0EA"},{name:"HP ProBook 450 G10",code:"ProBook 450 G10"},{name:"HP EliteBook 840 G11",code:"EliteBook 840 G11"}]},

  {deviceType:"masaustu-bilgisayar",brand:"lenovo",familySlug:"thinkcentre",familyName:"ThinkCentre",familyKind:"official-family",marketSourceUrl:DESKTOP,catalogBasis:"Akakçe pazar keşfi + Lenovo Türkiye ürün/destek",productUrl:"https://www.lenovo.com/tr/tr/desktops/",supportUrl:"https://support.lenovo.com/tr/tr/",manualUrl:"https://support.lenovo.com/tr/tr/",softwareUrl:"https://support.lenovo.com/tr/tr/",models:[{name:"ThinkCentre Neo 50t Gen 5 12UD001UTR",code:"12UD001UTR"},{name:"ThinkCentre Neo 50t Gen 5 12UB000BTR",code:"12UB000BTR"},{name:"ThinkCentre Neo 50t Gen 5 12UD004KTR",code:"12UD004KTR"},{name:"ThinkCentre Neo 50t Gen 5 12UD002CTR",code:"12UD002CTR"},{name:"ThinkCentre Neo 50t Gen 6 13BD007UTR",code:"13BD007UTR"},{name:"ThinkCentre M90t Gen 5 12V2S08100",code:"12V2S08100"}]},
  {deviceType:"masaustu-bilgisayar",brand:"dell",familySlug:"masaustu-modelleri",familyName:"Masaüstü Bilgisayar Modelleri",marketSourceUrl:DESKTOP,catalogBasis:"Akakçe pazar keşfi + Dell Türkiye Service Tag/model destek portalı",productUrl:"https://www.dell.com/tr-tr/shop/masa%C3%BCst%C3%BC-bilgisayarlar/sr/desktops",supportUrl:"https://www.dell.com/support/home/tr-tr",manualUrl:"https://www.dell.com/support/home/tr-tr",softwareUrl:"https://www.dell.com/support/home/tr-tr",models:[{name:"Dell Tower ECT1250",code:"ECT1250"},{name:"Vostro 3030 MT N6001VDT3030MTU",code:"N6001VDT3030MTU"},{name:"Vostro 3030 MT N6004VDT3030MTU",code:"N6004VDT3030MTU"}]},
  {deviceType:"masaustu-bilgisayar",brand:"hp",familySlug:"masaustu-modelleri",familyName:"Masaüstü Bilgisayar Modelleri",marketSourceUrl:DESKTOP,catalogBasis:"Akakçe pazar keşfi + HP Türkiye model destek/sürücü portalı",productUrl:"https://www.hp.com/tr-tr/shop/list.aspx?sel=DTP",supportUrl:"https://support.hp.com/tr-tr/",manualUrl:"https://support.hp.com/tr-tr/",softwareUrl:"https://support.hp.com/tr-tr/drivers",models:[{name:"HP 290 G9",code:"290 G9"},{name:"HP Pro Tower 290 G9 623Y0ET",code:"623Y0ET"},{name:"HP Elite Tower 800 G9 999Z5ET",code:"999Z5ET"}]},
  {deviceType:"masaustu-bilgisayar",brand:"asus",familySlug:"expertcenter",familyName:"ExpertCenter",familyKind:"official-family",marketSourceUrl:DESKTOP,catalogBasis:"Akakçe pazar keşfi + ASUS Türkiye ürün/destek",productUrl:"https://www.asus.com/tr/displays-desktops/tower-pcs/expertcenter/",supportUrl:"https://www.asus.com/tr/support/",manualUrl:"https://www.asus.com/tr/support/download-center/",softwareUrl:"https://www.asus.com/tr/support/download-center/",models:[{name:"ExpertCenter B900 B900MF-0072650110",code:"B900MF-0072650110"},{name:"ExpertCenter P500 P500MV-I513428512B0D",code:"P500MV-I513428512B0D"},{name:"ExpertCenter P500 P500MV-C52108512B0D",code:"P500MV-C52108512B0D"}]},
  {deviceType:"masaustu-bilgisayar",brand:"msi",familySlug:"masaustu-modelleri",familyName:"Masaüstü Bilgisayar Modelleri",marketSourceUrl:DESKTOP,catalogBasis:"Akakçe pazar keşfi + MSI Türkiye ürün/destek",productUrl:"https://tr.msi.com/Business-Productivity-PC",supportUrl:"https://tr.msi.com/support",manualUrl:"https://tr.msi.com/support/download",softwareUrl:"https://tr.msi.com/support/download",models:[{name:"PRO DP10 13M-002EU",code:"13M-002EU"},{name:"PRO DP21 14M",code:"PRO DP21 14M"}]}
];

const built=definitions.map(defineCatalog);
export const computingFamilies=built.map(x=>x.family);
export const computingModels=built.flatMap(x=>x.models);
