import {defineCatalog} from "./helpers.js";

const TV="https://www.akakce.com/televizyon.html";
const PRINTER="https://www.akakce.com/yazici.html";
const LASER="https://www.akakce.com/lazer-yazici.html";
const INK="https://www.akakce.com/murekkep-puskurtmeli-yazici.html";

const definitions=[
  {deviceType:"televizyon",brand:"samsung",familySlug:"televizyon-modelleri",familyName:"Televizyon Modelleri",marketSourceUrl:TV,catalogBasis:"Akakçe pazar keşfi + Samsung Türkiye model destek/kılavuz portalı",productUrl:"https://www.samsung.com/tr/tvs/all-tvs/",supportUrl:"https://www.samsung.com/tr/support/",manualUrl:"https://www.samsung.com/tr/support/user-manuals-and-guide/",softwareUrl:"https://www.samsung.com/tr/support/",models:[{name:"Crystal UHD 50U8000F",code:"UE50U8000FUXTK",supportUrl:"https://www.samsung.com/tr/support/model/UE50U8000FUXTK/",manualUrl:"https://www.samsung.com/tr/support/model/UE50U8000FUXTK/"},{name:"Crystal UHD 58U8000F",code:"UE58U8000F"},{name:"Neo QLED 65QN70F",code:"QE65QN70FAUXTK"},{name:"Neo QLED 75QN70F",code:"QE75QN70F"},{name:"QLED 65Q7F5",code:"QE65Q7F"},{name:"OLED 65S90F",code:"QE65S90FATXTK",supportUrl:"https://www.samsung.com/tr/support/model/QE65S90FATXTK/",manualUrl:"https://www.samsung.com/tr/support/model/QE65S90FATXTK/",softwareUrl:"https://www.samsung.com/tr/support/model/QE65S90FATXTK/"}]},
  {deviceType:"televizyon",brand:"lg",familySlug:"televizyon-modelleri",familyName:"Televizyon Modelleri",marketSourceUrl:TV,catalogBasis:"Akakçe pazar keşfi + LG Türkiye ürün/model destek sayfaları",productUrl:"https://www.lg.com/tr/tv-soundbar/tum-tvler/",supportUrl:"https://www.lg.com/tr/destek",manualUrl:"https://www.lg.com/tr/destek/urun-destegi",softwareUrl:"https://www.lg.com/tr/destek/urun-destegi",models:[{name:"UHD 55UA84006LB",code:"55UA84006LB",productUrl:"https://www.lg.com/tr/tv-soundbar/uhd-tv/55ua84006lb/"},{name:"OLED evo 55C64LA",code:"OLED55C64LA"},{name:"QNED 65QNED70B6C",code:"65QNED70B6C"},{name:"QNED 55QNED70B6C",code:"55QNED70B6C"},{name:"NanoCell 65NANO80A6B",code:"65NANO80A6B",productUrl:"https://www.lg.com/tr/tv-soundbar/nanocell/65nano80a6b/",manualUrl:"https://www.lg.com/tr/destek/urun-destegi/cs-65NANO80A6B/"},{name:"OLED 65B65LA",code:"OLED65B65LA"},{name:"StanbyME 2 27LX6TDGA",code:"27LX6TDGA"}]},
  {deviceType:"televizyon",brand:"tcl",familySlug:"televizyon-modelleri",familyName:"Televizyon Modelleri",marketSourceUrl:TV,catalogBasis:"Akakçe pazar keşfi + TCL Türkiye model destek listesi",productUrl:"https://www.tcl.com/tr/tr/tvs",supportUrl:"https://www.tcl.com/tr/tr/support-tv",manualUrl:"https://www.tcl.com/tr/tr/support-tv",softwareUrl:"https://www.tcl.com/tr/tr/support-tv",models:[{name:"55T8C",code:"55T8C",supportUrl:"https://www.tcl.com/tr/tr/support/model/55t8c",manualUrl:"https://www.tcl.com/tr/tr/support/model/55t8c"},{name:"65C6K",code:"65C6K",supportUrl:"https://www.tcl.com/tr/tr/support/model/65c6k",manualUrl:"https://www.tcl.com/tr/tr/support/model/65c6k"},{name:"55C6K",code:"55C6K",supportUrl:"https://www.tcl.com/tr/tr/support/model/55c6k",manualUrl:"https://www.tcl.com/tr/tr/support/model/55c6k"},{name:"75C6K",code:"75C6K",supportUrl:"https://www.tcl.com/tr/tr/support/model/75c6k",manualUrl:"https://www.tcl.com/tr/tr/support/model/75c6k"},{name:"55T61C",code:"55T61C"},{name:"65T61C",code:"65T61C"},{name:"32S5K",code:"32S5K"},{name:"43S5K",code:"43S5K"},{name:"65Q6C",code:"65Q6C",supportUrl:"https://www.tcl.com/tr/tr/support/model/65q6c",manualUrl:"https://www.tcl.com/tr/tr/support/model/65q6c"}]},
  {deviceType:"televizyon",brand:"onvo",familySlug:"televizyon-modelleri",familyName:"Televizyon Modelleri",marketSourceUrl:TV,catalogBasis:"Akakçe pazar keşfi + ONVO resmî Bilgi Merkezi model ve kılavuzları",productUrl:"https://onvo.com.tr/televizyon",supportUrl:"https://onvo.com.tr/bilgi-merkezi",manualUrl:"https://onvo.com.tr/bilgi-merkezi",models:[{name:"75VQ90F3UA",code:"75VQ90F3UA"},{name:"65VQ90F3UA",code:"65VQ90F3UA"},{name:"55VQ90F3UA",code:"55VQ90F3UA"},{name:"50VQ90F3UA",code:"50VQ90F3UA"},{name:"32VQ80F2HA",code:"32VQ80F2HA"},{name:"32OVM6500X",code:"32OVM6500X"}]},
  {deviceType:"televizyon",brand:"philips",familySlug:"televizyon-modelleri",familyName:"Televizyon Modelleri",marketSourceUrl:TV,catalogBasis:"Akakçe pazar keşfi + Philips Türkiye TV ürün/destek sayfaları",productUrl:"https://www.philips.com.tr/c-m-so/tv",supportUrl:"https://www.philips.com.tr/c-w/support-home.html",manualUrl:"https://www.philips.com.tr/c-w/support-home.html",softwareUrl:"https://www.philips.com.tr/c-w/support-home.html",models:[{name:"OLED 4K Ambilight 55OLED810/12",code:"55OLED810/12",productUrl:"https://www.philips.com.tr/c-p/55OLED810_12/oled-4k-ambilight-tv",manualUrl:"https://www.philips.com.tr/c-p/55OLED810_12/oled-4k-ambilight-tv/destek"},{name:"OLED Ambilight 55OLED760/12",code:"55OLED760/12"},{name:"The One 55PUS9000/12",code:"55PUS9000/12"}]},
  {deviceType:"televizyon",brand:"grundig",familySlug:"televizyon-modelleri",familyName:"Televizyon Modelleri",marketSourceUrl:TV,catalogBasis:"Akakçe pazar keşfi + Grundig Türkiye ürün/destek",productUrl:"https://www.grundig.com.tr/televizyon",supportUrl:"https://www.grundig.com.tr/destek",manualUrl:"https://www.grundig.com.tr/destek",models:[{name:"65 GQ 950 A",code:"65 GQ 950 A"},{name:"50 GQ 750 A",code:"50 GQ 750 A"},{name:"55 GHU 8500 A",code:"55 GHU 8500 A"}]},
  {deviceType:"televizyon",brand:"vestel",familySlug:"televizyon-modelleri",familyName:"Televizyon Modelleri",marketSourceUrl:TV,catalogBasis:"Akakçe pazar keşfi + Vestel Türkiye ürün/destek",productUrl:"https://www.vestel.com.tr/televizyonlar-c-1",supportUrl:"https://www.vestel.com.tr/destek",manualUrl:"https://www.vestel.com.tr/destek/kullanim-kilavuzlari",softwareUrl:"https://www.vestel.com.tr/destek",models:[{name:"75UV9750",code:"75UV9750"},{name:"65QA9700",code:"65QA9700"},{name:"55QA9700",code:"55QA9700"}]},

  {deviceType:"yazici",brand:"canon",familySlug:"pixma",familyName:"PIXMA",familyKind:"official-family",marketSourceUrl:INK,catalogBasis:"Akakçe mürekkep püskürtmeli envanteri + Canon Türkiye model destek",productUrl:"https://www.canon.com.tr/printers/pixma-inkjet-printers/",supportUrl:"https://www.canon.com.tr/support/",manualUrl:"https://www.canon.com.tr/support/",softwareUrl:"https://www.canon.com.tr/support/",models:[{name:"PIXMA G3470",code:"G3470"},{name:"PIXMA G3410",code:"G3410"},{name:"PIXMA G3416",code:"G3416"},{name:"PIXMA G3430",code:"G3430"}]},
  {deviceType:"yazici",brand:"canon",familySlug:"i-sensys",familyName:"i-SENSYS",familyKind:"official-family",marketSourceUrl:LASER,catalogBasis:"Akakçe lazer yazıcı envanteri + Canon Türkiye model destek",productUrl:"https://www.canon.com.tr/business/products/office-printers/multifunction/colour/i-sensys/",supportUrl:"https://www.canon.com.tr/support/",manualUrl:"https://www.canon.com.tr/support/",softwareUrl:"https://www.canon.com.tr/support/",models:[{name:"i-SENSYS MF664Cdw",code:"MF664Cdw"},{name:"i-SENSYS MF655Cdw",code:"MF655Cdw"},{name:"i-SENSYS MF463dw",code:"MF463dw"}]},
  {deviceType:"yazici",brand:"epson",familySlug:"ecotank",familyName:"EcoTank",familyKind:"official-family",marketSourceUrl:INK,catalogBasis:"Akakçe mürekkep püskürtmeli envanteri + Epson Türkiye ürün/destek",productUrl:"https://www.epson.com.tr/tr_TR/%C3%BCr%C3%BCnler/yaz%C4%B1c%C4%B1lar/inkjet/t%C3%BCketici/ecotank/c/consumer-ecotank",supportUrl:"https://www.epson.com.tr/support",manualUrl:"https://www.epson.com.tr/support",softwareUrl:"https://www.epson.com.tr/support",models:["EcoTank L3250","EcoTank L3260","EcoTank L3270","EcoTank L4260","EcoTank L6270"]},
  {deviceType:"yazici",brand:"hp",familySlug:"laserjet",familyName:"LaserJet",familyKind:"official-family",marketSourceUrl:LASER,catalogBasis:"Akakçe lazer yazıcı envanteri + HP Türkiye model destek/sürücü portalı",productUrl:"https://www.hp.com/tr-tr/printers/laserjet-printers.html",supportUrl:"https://support.hp.com/tr-tr/",manualUrl:"https://support.hp.com/tr-tr/",softwareUrl:"https://support.hp.com/tr-tr/drivers",models:[{name:"Laser MFP 137fnw",code:"4ZB84A"},{name:"LaserJet MFP M141w",code:"7MD74A"},{name:"LaserJet MFP M236dw",code:"9YF95A"},{name:"LaserJet Pro 4003dw",code:"2Z610A"}]},
  {deviceType:"yazici",brand:"brother",familySlug:"inkbenefit-tank",familyName:"InkBenefit Tank",familyKind:"official-family",marketSourceUrl:INK,catalogBasis:"Akakçe mürekkep püskürtmeli envanteri + Brother Türkiye ürün/kılavuz/sürücü",productUrl:"https://www.brother.com.tr/printers/inkjet-printers",supportUrl:"https://www.brother.com.tr/support",manualUrl:"https://support.brother.com/",softwareUrl:"https://support.brother.com/",models:["DCP-T430W","DCP-T530DW","DCP-T730DW","DCP-T830DW","DCP-T220"]},
  {deviceType:"yazici",brand:"brother",familySlug:"lazer-yazicilar",familyName:"Lazer Yazıcılar",marketSourceUrl:LASER,catalogBasis:"Akakçe lazer yazıcı envanteri + Brother Türkiye ürün/kılavuz/sürücü",productUrl:"https://www.brother.com.tr/printers/laser-printers",supportUrl:"https://www.brother.com.tr/support",manualUrl:"https://support.brother.com/",softwareUrl:"https://support.brother.com/",models:["MFC-L2806DW","DCP-L3560CDW","HL-1211W","MFC-L3720CDW","HL-L2461DN"]},
  {deviceType:"yazici",brand:"xerox",familySlug:"lazer-yazicilar",familyName:"Lazer Yazıcılar",marketSourceUrl:LASER,catalogBasis:"Akakçe lazer yazıcı envanteri + Xerox resmî model destek/sürücü",productUrl:"https://www.xerox.com/tr-tr/ofis/urunler/yazicilar",supportUrl:"https://www.support.xerox.com/tr-tr",manualUrl:"https://www.support.xerox.com/tr-tr",softwareUrl:"https://www.support.xerox.com/tr-tr",models:["Phaser 3020V_BI","B225","B235"]},
  {deviceType:"yazici",brand:"pantum",familySlug:"lazer-yazicilar",familyName:"Lazer Yazıcılar",marketSourceUrl:LASER,catalogBasis:"Akakçe lazer yazıcı envanteri + Pantum Türkiye resmî ürün/sürücü portalı",productUrl:"https://www.pantum.com.tr/urunler/",supportUrl:"https://drivers.pantum.com.tr/",manualUrl:"https://drivers.pantum.com.tr/",softwareUrl:"https://drivers.pantum.com.tr/",models:["P2500W","M6500NW","BM2300AW"]}
];

const built=definitions.map(defineCatalog);
export const displayPrintFamilies=built.map(x=>x.family);
export const displayPrintModels=built.flatMap(x=>x.models);
