export const VERIFIED_AT="2026-08-25";

export function slugify(value=""){
  return String(value).toLocaleLowerCase("tr-TR").normalize("NFD")
    .replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i")
    .replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
}

const clusterTemplates={
  "robot-supurge":[
    {slug:"sarj-ve-istasyon",title:"Şarj / istasyona dönüş sorunu",risk:"low",summary:"Şarj temas yüzeyleri, istasyonun beslemesi ve istasyon çevresindeki engeller kullanıcı seviyesinde kontrol edilir.",steps:["Cihazı kapatın; istasyonun prize bağlı ve göstergesinin normal olduğunu doğrulayın.","Yalnızca dışarıdan erişilen şarj temaslarını kuru, yumuşak bir bezle temizleyin.","İstasyonun önü ve iki yanı için kılavuzdaki boşluk şartlarını sağlayıp yeniden deneyin."],stopWhen:"Temaslarda yanık izi, sıvı, aşırı ısınma varsa veya cihaz hâlâ şarj olmuyorsa kullanmayı bırakıp resmî desteğe geçin.",safety:"Batarya paketini, istasyonu veya adaptörü açmayın; farklı model adaptör kullanmayın."},
    {slug:"harita-ve-navigasyon",title:"Harita / navigasyon sorunu",risk:"low",summary:"Sensörlerin dış yüzeyi, uygulamadaki harita seçimi ve temizlik alanındaki fiziksel engeller kontrol edilir.",steps:["Uygulamada doğru ev ve haritanın seçili olduğunu doğrulayın.","Kılavuzda gösterilen sensörlerin yalnızca dış yüzeylerini kuru bezle temizleyin.","Cihazı açık bir alanda başlatıp haritayı yeniden yüklemeyi deneyin."],stopWhen:"Sensör kapağı hasarlıysa, cihaz düşmüşse veya hata tekrar ediyorsa sökmeden resmî desteğe geçin.",safety:"Lidar, kamera veya sensör modülünü açmayın ve optik yüzeylerde kimyasal temizleyici kullanmayın."},
    {slug:"firca-filtre-su-akisi",title:"Fırça, filtre veya paspas akışı",risk:"low",summary:"Kullanıcı tarafından çıkarılabilir fırça, filtre, hazne ve paspas parçaları kılavuza göre kontrol edilir.",steps:["Cihazı kapatın ve hareketli fırçaların tamamen durmasını bekleyin.","Yalnızca kılavuzda kullanıcı bakımına açılan fırça, filtre ve hazneleri çıkarın.","Saç ve görünür tıkanıklıkları temizleyip tamamen kuru parçaları doğru yönde yeniden takın."],stopWhen:"Motor sesi değişmişse, sıvı elektronik bölüme ulaştıysa veya parça dönmüyorsa cihazı çalıştırmayın.",safety:"Motor, pompa, elektronik kart ve batarya bölmesine müdahale etmeyin."}
  ],
  "dikey-supurge":[
    {slug:"cekis-ve-hava-yolu",title:"Çekiş düşmesi / hava yolu uyarısı",risk:"low",summary:"Hazne doluluğu, kullanıcı erişimli hava yolu, başlık ve filtre kılavuza göre kontrol edilir.",steps:["Cihazı kapatın ve şarjdan ayırın.","Hazneyi boşaltın; boru ve başlıkta dışarıdan görülen tıkanıklıkları kontrol edin.","Filtreyi üreticinin temizlik ve kurutma talimatına göre yeniden takın."],stopWhen:"Motor gövdesinde tıkanıklık, yanık kokusu veya anormal ısınma varsa kullanmayı bırakın.",safety:"Motor gövdesini açmayın; kesici veya metal cisimleri hava kanalına sokmayın."},
    {slug:"sarj-ve-batarya",title:"Şarj / çalışma süresi sorunu",risk:"medium",summary:"Resmî şarj cihazı, duvar prizi, dış temaslar ve ortam sıcaklığı kullanıcı seviyesinde kontrol edilir.",steps:["Yalnızca modelin resmî şarj cihazını kullanın.","Prizi ve kablonun dış yüzeyini hasar açısından kontrol edin.","Kılavuzdaki şarj sıcaklığı ve tam şarj süresine uyup yeniden deneyin."],stopWhen:"Bataryada şişme, koku, sıvı, darbe veya aşırı ısınma varsa şarj etmeyin ve resmî servise başvurun.",safety:"Batarya paketini açmayın, hücre değiştirmeyin ve üçüncü taraf adaptör kullanmayın."},
    {slug:"firca-basligi",title:"Fırça / başlık dönmüyor",risk:"low",summary:"Başlığın dıştan erişilen fırçası, bağlantısı ve görünür tıkanıklıkları kontrol edilir.",steps:["Cihazı tamamen kapatıp başlığı ayırın.","Kılavuzun izin verdiği fırça kapağını açarak saç ve ipleri temizleyin.","Başlığı doğru oturtup düşük güçte yeniden deneyin."],stopWhen:"Tahrik mili sıkışmışsa, kablo görünüyorsa veya başlık aşırı ısınıyorsa kullanmayın.",safety:"Başlık motorunu veya elektronik bağlantıyı sökmeyin."}
  ],
  "kahve-makinesi":[
    {slug:"su-akisi-ve-demleme",title:"Su akışı / demleme başlamıyor",risk:"low",summary:"Su haznesinin oturuşu, seçilen içecek, kullanıcı erişimli çıkışlar ve resmî durulama adımları kontrol edilir.",steps:["Su haznesini kılavuzdaki seviyeye kadar doldurup doğru oturttuğunuzu doğrulayın.","Kapsül, çekirdek veya filtre bölümünü model tipine göre kontrol edin.","Kılavuzdaki durulama ya da sıcak su işlemini uygulayın."],stopWhen:"Makinenin içinde su kaçağı, elektrik kokusu veya hata devamı varsa fişi çekip resmî desteğe geçin.",safety:"Isıtıcı, pompa, öğütücü veya kapalı gövdeyi açmayın; sıcak çıkışlara dokunmayın."},
    {slug:"kirec-ve-temizlik",title:"Kireç / temizlik uyarısı",risk:"low",summary:"Yalnızca üreticinin belirttiği kireç çözme ürünü ve modelin resmî programı kullanılır.",steps:["Kılavuzdaki uyarının kireç çözme veya temizlik döngüsüne ait olduğunu doğrulayın.","Üreticinin onayladığı ürünü belirtilen oranda hazırlayın.","Programı yarıda kesmeden tamamlayıp istenen durulama döngülerini uygulayın."],stopWhen:"Program başlamıyor, sıvı gövde içine kaçıyor veya pompa anormal ses çıkarıyorsa servise geçin.",safety:"Sirke veya markanın onaylamadığı kimyasalları kullanmayın; sıcak su devresini açmayın."},
    {slug:"sut-ve-kahve-cikisi",title:"Süt / kahve çıkışı zayıf",risk:"low",summary:"Çıkarılabilir süt sistemi, çıkış ağzı ve kullanıcı bakımına açık parçalar resmî temizlik adımıyla kontrol edilir.",steps:["Makineyi kapatıp sıcak parçaların soğumasını bekleyin.","Yalnızca kılavuzda çıkarılabilir gösterilen süt ve kahve çıkış parçalarını temizleyin.","Parçaları tamamen kurutup doğru yönde yeniden takın."],stopWhen:"Buhar kaçışı, yanık koku veya iç kaçak varsa cihazı kullanmayın.",safety:"Buhar kazanını, termobloku, pompayı veya öğütücüyü sökmeyin."}
  ],
  "dizustu-bilgisayar":[
    {slug:"acilis-ve-guc",title:"Açılmıyor / güç belirtisi yok",risk:"low",summary:"Resmî adaptör, priz, harici aygıtlar ve üreticinin kullanıcı seviyesindeki güç sıfırlama adımı kontrol edilir.",steps:["Modelin resmî adaptörünü takın ve prizde enerji olduğunu doğrulayın.","USB, dock ve haricî ekran dahil tüm aksesuarları çıkarın.","Üreticinin model için verdiği güç sıfırlama adımı varsa aynen uygulayın."],stopWhen:"Sıvı teması, batarya şişmesi, yanık kokusu veya düşme varsa cihazı açmayı denemeyin.",safety:"Kapalı kasayı, bataryayı veya anakartı açmayın; farklı voltajlı adaptör kullanmayın."},
    {slug:"surucu-ve-baglanti",title:"Wi‑Fi / ses / çevre birimi sürücüsü",risk:"low",summary:"İşletim sistemi güncellemesi ve yalnızca üreticinin model destek sayfasındaki sürücüler kullanılır.",steps:["İşletim sisteminin yerleşik sorun gidericisini ve güncellemelerini kontrol edin.","Cihaz yöneticisinde hata görünen bileşenin adını kaydedin.","Yalnızca modelin resmî sürücü sayfasındaki doğru işletim sistemi paketini kullanın."],stopWhen:"Şifreleme, kurumsal yönetim veya veri kaybı riski varsa değişiklik yapmadan BT desteğine geçin.",safety:"Üçüncü taraf sürücü paketi veya kaynağı belirsiz BIOS dosyası kullanmayın."},
    {slug:"ekran-ve-isletim-sistemi",title:"Ekran gelmiyor / işletim sistemi başlamıyor",risk:"medium",summary:"Parlaklık, haricî ekran, güvenli kurtarma seçenekleri ve üreticinin tanılama aracı kontrol edilir.",steps:["Parlaklığı artırın ve haricî ekran/dock bağlantılarını çıkarın.","Üreticinin açılış tanılama tuşunu veya resmî kurtarma menüsünü kullanın.","Hata kodunu ve LED/bip desenini kaydedin."],stopWhen:"Diskte önemli veri varsa, tekrar eden kapanma veya fiziksel ekran hasarı görülüyorsa servise geçin.",safety:"Ekran panelini, kapalı kasayı veya anakartı sökmeyin; veri silen kurtarma işlemini yedeksiz başlatmayın."}
  ],
  "masaustu-bilgisayar":[
    {slug:"post-ve-acilis",title:"POST / açılış sorunu",risk:"medium",summary:"Güç kablosu, ekran girişi, haricî aygıtlar ve üreticinin LED/bip tanılama kodları kontrol edilir.",steps:["Bilgisayarı kapatın; güç ve ekran kablolarını dıştan kontrol edin.","USB aygıtları ve ikinci ekranları çıkarıp yeniden deneyin.","Üreticinin resmî destek sayfasındaki LED veya bip kodunu kaydedin."],stopWhen:"Yanık kokusu, sıvı, kıvılcım veya güç kaynağı sesi varsa fişi çekip servise geçin.",safety:"Güç kaynağını, anakartı veya ekran kartını açmayın; enerji bağlıyken kasa içine müdahale etmeyin."},
    {slug:"surucu-ve-ag",title:"Sürücü / ağ / ses sorunu",risk:"low",summary:"Yalnızca üreticinin model ve işletim sistemiyle eşleşen sürücüleri kullanılır.",steps:["İşletim sistemi güncellemelerini ve aygıt yöneticisi hatalarını kontrol edin.","Model kodunu resmî destek sayfasında doğrulayın.","Gerekli sürücüyü üreticinin portalından indirip yeniden başlatın."],stopWhen:"Kurumsal ağ politikası, disk şifreleme veya kritik veri söz konusuysa BT desteğine geçin.",safety:"Üçüncü taraf sürücü arşivleri ve resmî olmayan BIOS dosyaları kullanmayın."},
    {slug:"goruntu-ve-depolama",title:"Görüntü / depolama algılama sorunu",risk:"medium",summary:"Haricî kablolar, BIOS tanılama ekranı ve üreticinin güvenli tanılama aracı kontrol edilir.",steps:["Farklı bir ekran girişi ve sağlam olduğu bilinen kabloyu deneyin.","Üreticinin yerleşik tanılama menüsünü çalıştırın.","Görünen hata kodunu kaydedip resmî destekle paylaşın."],stopWhen:"Disk tıklama sesi, veri kaybı, aşırı ısınma veya güç kesilmesi varsa cihazı kullanmayı bırakın.",safety:"Güç kaynağını veya depolama birimini enerji bağlıyken açmayın; veri kurtarma denemelerini çoğaltmayın."}
  ],
  "televizyon":[
    {slug:"goruntu-ve-giris",title:"Görüntü yok / yanlış giriş",risk:"low",summary:"Giriş kaynağı, HDMI kablosu, bağlı cihaz ve resmî görüntü testi kontrol edilir.",steps:["TV menüsünden doğru giriş kaynağını seçin.","Bağlı cihazı kapatıp HDMI kablosunu yeniden takın.","Model destekliyorsa resmî kendi kendine tanılama görüntü testini çalıştırın."],stopWhen:"Panel çatlağı, sıvı, yanık kokusu veya arka aydınlatma arızası şüphesi varsa servise geçin.",safety:"TV arka kapağını açmayın; panel ve güç kartı yüksek gerilim riski taşır."},
    {slug:"ses-ve-uygulama",title:"Ses / uygulama sorunu",risk:"low",summary:"Ses çıkışı seçimi, uygulama güncellemesi ve resmî yazılım güncelleme menüsü kontrol edilir.",steps:["Ses çıkışının TV hoparlörü veya doğru haricî cihaza ayarlı olduğunu doğrulayın.","Sorunlu uygulamayı kapatıp TV'yi yeniden başlatın.","Yazılımı yalnızca TV'nin resmî güncelleme menüsünden veya model destek sayfasından güncelleyin."],stopWhen:"Güncelleme kesiliyor veya cihaz sürekli yeniden başlıyorsa servise geçin.",safety:"Resmî olmayan firmware dosyası yüklemeyin ve güncelleme sırasında gücü kesmeyin."},
    {slug:"ag-ve-kumanda",title:"Wi‑Fi / kumanda bağlantısı",risk:"low",summary:"Ağ yeniden başlatma, kumanda pili/eşleştirmesi ve tarih-saat ayarları kontrol edilir.",steps:["Modem ve TV'yi kapatıp yeniden başlatın.","Kumanda pillerini doğru kutupla takın ve modelin eşleştirme adımını uygulayın.","TV tarih-saat ve ağ ayarlarını otomatik moda alın."],stopWhen:"Kumanda veya TV sıvı aldıysa ya da ağ modülü hiç görünmüyorsa servise geçin.",safety:"TV içindeki ağ kartına veya güç devresine müdahale etmeyin."}
  ],
  "yazici":[
    {slug:"kagit-besleme",title:"Kağıt sıkışması / besleme sorunu",risk:"low",summary:"Kağıt yolu, tepsi kılavuzları ve üreticinin kullanıcı erişimine açtığı kapaklar kontrol edilir.",steps:["Yazıcıyı kapatın ve kılavuzda belirtilen süre kadar soğumasını bekleyin.","Kağıdı kılavuzdaki yönde, yırtmadan yavaşça çıkarın.","Tepsi kılavuzlarını kağıt boyutuna göre ayarlayıp hasarlı kağıtları ayırın."],stopWhen:"Kağıt yırtılıp içeride kaldıysa, fuser bölgesi sıcaksa veya mekanizma zorlanıyorsa servise geçin.",safety:"Lazer yazıcının fuser bölümüne dokunmayın; metal alet kullanmayın."},
    {slug:"baski-kalitesi",title:"Soluk / çizgili / lekeli baskı",risk:"low",summary:"Sarf seviyesi, doğru kağıt türü ve yazıcının resmî bakım/temizleme programı kontrol edilir.",steps:["Sarf seviyesini yazıcının paneli veya resmî yazılımından kontrol edin.","Doğru kağıt türü ve baskı kalitesi ayarını seçin.","Üreticinin bakım menüsündeki nozül, kafa veya kalite temizleme işlemini uygulayın."],stopWhen:"Toner/mürekkep sızıntısı, tekrarlayan mekanik ses veya bakım sonrası düzelmeme varsa servise geçin.",safety:"Toner kartuşunu delmeyin, fuser veya lazer ünitesini açmayın."},
    {slug:"cevrimdisi-ve-surucu",title:"Çevrimdışı / sürücü / Wi‑Fi sorunu",risk:"low",summary:"Kuyruk, ağ bağlantısı ve yalnızca üreticinin resmî sürücü paketi kontrol edilir.",steps:["Yazdırma kuyruğunu ve varsayılan yazıcı seçimini kontrol edin.","Yazıcı ve modemi yeniden başlatıp aynı ağa bağlı olduklarını doğrulayın.","Modelin resmî destek sayfasından doğru işletim sistemi sürücüsünü kurun."],stopWhen:"Kurumsal ağ politikası veya yönetici parolası gerekiyorsa ağ yöneticisine geçin.",safety:"Üçüncü taraf sürücü paketleri veya kaynağı belirsiz firmware kullanmayın."}
  ],
  "klima":[
    {slug:"filtre-ve-hava-akisi",title:"Hava akışı zayıf / filtre uyarısı",risk:"low",summary:"Kullanıcı erişimli filtre, hava giriş-çıkış engelleri ve kumanda fan ayarı kontrol edilir.",steps:["Klimayı kumandadan kapatın ve güvenli bakım için kılavuzdaki enerji kesme adımını izleyin.","Yalnızca kullanıcı tarafından çıkarılabilir filtreyi kılavuza göre temizleyip tamamen kurutun.","İç ve dış ünitenin hava giriş-çıkışını kapatan eşyaları uzaklaştırın."],stopWhen:"Buzlanma, suyun elektrik bölümüne akması veya anormal ses varsa cihazı kapatıp servise geçin.",safety:"Soğutucu devresine, kompresöre, elektrik kartına veya kapalı panellere müdahale etmeyin."},
    {slug:"kumanda-ve-mod",title:"Kumanda / çalışma modu sorunu",risk:"low",summary:"Kumanda pili, mod, hedef sıcaklık, zamanlayıcı ve resmî reset adımları kontrol edilir.",steps:["Kumanda pillerini doğru kutupla takın ve ekranı kontrol edin.","Soğutma/ısıtma modu ile hedef sıcaklığın ortam koşuluna uygun olduğunu doğrulayın.","Zamanlayıcı ve uyku modunu kapatıp cihazı yeniden deneyin."],stopWhen:"Sigorta tekrar atıyor, elektrik kokusu veya hata kodu devam ediyorsa servise geçin.",safety:"Elektrik panosu, kapasitör veya iç/dış ünite kartını açmayın."},
    {slug:"sogutmuyor-isitmiyor",title:"Yeterince soğutmuyor / ısıtmıyor",risk:"medium",summary:"Mod, hedef sıcaklık, filtre, kapı-pencere ve üreticinin normal bekleme/defrost koşulları kontrol edilir.",steps:["Doğru modu ve hedef sıcaklığı seçip kılavuzdaki stabil çalışma süresini bekleyin.","Kapı ve pencereleri kapatın; filtre ve hava akışını kontrol edin.","Dış ünitenin önü kapalıysa güvenli mesafeden engeli kaldırın."],stopWhen:"Soğutucu kaçağı şüphesi, buzlanma, yağ izi veya performans kaybı sürüyorsa servise geçin.",safety:"Gaz dolumu/boşaltımı, boru bağlantısı, kaçak testi ve kompresör işlemleri yalnızca yetkili servis içindir."}
  ],
  "elektrikli-scooter":[
    {slug:"sarj-olmuyor",title:"Şarj olmuyor / şarj kesiliyor",risk:"high",summary:"Cihazın kapalı olması, ortam sıcaklığı, resmî şarj cihazı ve portun dış görünümü kontrol edilir; batarya paketi açılmaz.",steps:["Scooter'ı kapatın ve kılavuzdaki şarj sıcaklığı aralığında bekletin.","Yalnızca modelin resmî şarj cihazını kullanın; kablo ve portta dış hasar olup olmadığını kontrol edin.","Şarj göstergesini kılavuzdaki normal durumla karşılaştırın."],stopWhen:"Portta yanık, sıvı, eğilmiş temas, bataryada şişme/koku/ısı veya tekrar eden kesilme varsa şarj etmeyin.",safety:"Batarya paketi, BMS, kontrolcü ve şarj cihazını açmayın; hücre, sigorta veya kablo onarımı yapmayın."},
    {slug:"uygulama-ve-firmware",title:"Uygulama / eşleştirme / firmware",risk:"low",summary:"Resmî uygulama, Bluetooth/konum izinleri, doğru hesap bölgesi ve üreticinin güncelleme akışı kontrol edilir.",steps:["Yalnızca üreticinin resmî uygulamasını kullanın.","Telefon Bluetooth ve gerekli uygulama izinlerini kontrol edin.","Güncellemeyi tam şarjlı telefonla, kesintisiz bağlantıda uygulama içinden başlatın."],stopWhen:"Güncelleme yarıda kaldıysa veya scooter açılmıyorsa yeniden yazılım yüklemeye çalışmadan resmî desteğe geçin.",safety:"Üçüncü taraf firmware, hız kilidi kaldırma veya kontrolcü yazılımı yayımlanmaz ve uygulanmaz."},
    {slug:"fren-lastik-ve-guvenlik",title:"Fren / lastik / sürüş güvenliği",risk:"high",summary:"Sürüş öncesi yalnızca dış gözlemle lastik, fren kolu, katlama mekanizması, ışık ve gevşeklik kontrol edilir.",steps:["Scooter kapalıyken lastiklerde hasar ve kılavuzdaki basınç değerini kontrol edin.","Fren kolunu ve katlama kilidini hareket ettirmeden önce dıştan kontrol edin.","Işık, reflektör ve zilin çalıştığını güvenli alanda doğrulayın."],stopWhen:"Fren zayıfsa, gidon/katlama kilidi gevşekse, lastik hasarlıysa veya hata kodu varsa sürmeyin.",safety:"Fren kaliperi ayarı, teker sökümü, motor, kontrolcü veya batarya işlemleri servis seviyesidir."}
  ]
};

export function buildSymptomClusters(deviceType,sourceUrl,sourceLabel="Resmî model kılavuzu / destek"){
  return (clusterTemplates[deviceType]||[]).map(cluster=>({...cluster,userCanTry:cluster.risk!=="high",source:{label:sourceLabel,url:sourceUrl}}));
}

export function defineCatalog(definition){
  const family={
    deviceType:definition.deviceType,brand:definition.brand,slug:definition.familySlug,name:definition.familyName,
    familyKind:definition.familyKind||"neutral-collection",catalogBasis:definition.catalogBasis,
    marketSourceUrl:definition.marketSourceUrl,verifiedAt:VERIFIED_AT
  };
  const models=definition.models.map(value=>{
    const item=typeof value==="string"?{name:value}:value;
    const name=item.name;
    const code=item.code||name;
    const slug=item.slug||slugify(code);
    const productUrl=item.productUrl||definition.productUrl;
    const supportUrl=item.supportUrl||definition.supportUrl||productUrl;
    const manualUrl=item.manualUrl||definition.manualUrl||supportUrl;
    const sourceUrl=manualUrl||supportUrl||productUrl;
    const softwareUrl=item.softwareUrl||definition.softwareUrl;
    return {
      deviceType:definition.deviceType,brand:definition.brand,family:definition.familySlug,slug,name,modelCode:code,
      productUrl,supportUrl,manualUrl,verifiedAt:VERIFIED_AT,indexable:true,
      verificationLevel:item.verificationLevel||(item.productUrl||item.manualUrl?"official-model":"market-and-official-support"),
      officialLabel:item.officialLabel||`${name} resmî ürün / destek kaynağı`,
      marketSource:{label:"Akakçe Türkiye pazar envanteri keşfi",url:definition.marketSourceUrl,role:"market-discovery-only"},
      softwareResources:softwareUrl?[{label:definition.softwareLabel||"Resmî yazılım / sürücü / firmware",url:softwareUrl,note:"Model ve işletim sistemi eşleşmesini üreticinin resmî sayfasında doğrulayın; üçüncü taraf dosya kullanmayın."}]:[],
      symptomClusters:buildSymptomClusters(definition.deviceType,sourceUrl,`${name} resmî kılavuz / destek`)
    };
  });
  return {family,models};
}
