import {defineCatalog} from "./helpers.js";

const ROBOT="https://www.akakce.com/robot-supurge.html";
const STICK="https://www.akakce.com/dikey-supurge.html";
const ESPRESSO="https://www.akakce.com/espresso-makinesi.html";
const FILTER="https://www.akakce.com/filtre-kahve-makinesi.html";
const CAPSULE="https://www.akakce.com/kapsul-kahve-makinesi.html";

const definitions=[
  {deviceType:"robot-supurge",brand:"roborock",familySlug:"robot-supurge-modelleri",familyName:"Robot Süpürge Modelleri",marketSourceUrl:ROBOT,catalogBasis:"Akakçe pazar keşfi + Roborock Türkiye ürün kataloğu ve resmî destek",productUrl:"https://tr.roborock.com/collections/robot-vacuum",supportUrl:"https://help.roborock.com/",manualUrl:"https://support.roborock.com/",softwareUrl:"https://help.roborock.com/",models:["Saros 10R","Saros 10","S8 MaxV Ultra","Qrevo L","Qrevo Curv","Q8 Max Pro","S8 Pro","S9"]},
  {deviceType:"robot-supurge",brand:"dreame",familySlug:"robot-supurge-modelleri",familyName:"Robot Süpürge Modelleri",marketSourceUrl:ROBOT,catalogBasis:"Akakçe pazar keşfi + Dreame Türkiye ürün desteği ve kılavuz merkezi",productUrl:"https://dreametech.com.tr/collections/robot-supurge",supportUrl:"https://dreametech.com.tr/pages/product-support",manualUrl:"https://dreametech.com.tr/pages/kullanici-kilavuzu",softwareUrl:"https://dreametech.com.tr/pages/product-support",models:["X50 Ultra Complete","X50 Pro Ultra Complete","X40 Ultra","X60 Ultra Complete","L40 Ultra AE","L10s Pro Ultra Heat","L10s Ultra Gen 2","L10s Pro Gen 2","L10s Plus"]},
  {deviceType:"robot-supurge",brand:"xiaomi",familySlug:"robot-vacuum",familyName:"Robot Vacuum",familyKind:"official-family",marketSourceUrl:ROBOT,catalogBasis:"Akakçe pazar keşfi + Xiaomi Türkiye Temizlik Cihazları kataloğu",productUrl:"https://www.mi.com/tr/event/cleaning-appliances/",supportUrl:"https://www.mi.com/tr/support/",manualUrl:"https://www.mi.com/tr/support/user-guide/",softwareUrl:"https://www.mi.com/tr/support/",models:[
    {name:"Robot Vacuum X20 Max",productUrl:"https://www.mi.com/tr/product/xiaomi-robot-vacuum-x20-max/"},
    {name:"Robot Vacuum X20 Pro",productUrl:"https://www.mi.com/tr/product/xiaomi-robot-vacuum-x20-pro/",manualUrl:"https://www.mi.com/tr/product/xiaomi-robot-vacuum-x20-pro/specs/"},
    {name:"Robot Vacuum X20+",productUrl:"https://www.mi.com/tr/product/xiaomi-robot-vacuum-x20-plus/"},
    {name:"Robot Vacuum H40",productUrl:"https://www.mi.com/tr/product/xiaomi-robot-vacuum-h40/",manualUrl:"https://www.mi.com/tr/product/xiaomi-robot-vacuum-h40/specs/"},
    "Robot Vacuum S10T","Vacuum 5","Vacuum 5 Pro","Vacuum S40 Pro"
  ]},
  {deviceType:"robot-supurge",brand:"ecovacs",familySlug:"deebot",familyName:"DEEBOT",familyKind:"official-family",marketSourceUrl:ROBOT,catalogBasis:"Akakçe pazar keşfi + ECOVACS Türkiye resmî kılavuz listesi",productUrl:"https://www.ecovacs.com/tr/deebot",supportUrl:"https://help.ecovacs.com/tr/support",manualUrl:"https://help.ecovacs.com/tr/support/owners-manuals",softwareUrl:"https://help.ecovacs.com/tr/support",models:["DEEBOT T90 OMNI","DEEBOT T90 PRO OMNI","DEEBOT T30C","DEEBOT T30 PRO OMNI","DEEBOT X8 PRO OMNI","DEEBOT T80 OMNI"]},
  {deviceType:"robot-supurge",brand:"philips",familySlug:"homerun",familyName:"HomeRun",familyKind:"official-family",marketSourceUrl:ROBOT,catalogBasis:"Akakçe pazar keşfi + Philips Türkiye HomeRun ürün/destek sayfaları",productUrl:"https://www.philips.com.tr/c-m-ho/elektrikli-supurgeler/robot-supurge",supportUrl:"https://www.philips.com.tr/c-w/support-home.html",manualUrl:"https://www.philips.com.tr/c-w/support-home.html",models:[{name:"HomeRun 9000 Serisi XU9100/10",code:"XU9100/10"},{name:"HomeRun 7000 Serisi Aqua XU7100/01",code:"XU7100/01"},{name:"HomeRun 7000 Serisi Aqua XU7000/01",code:"XU7000/01"},{name:"HomeRun 5000 Serisi XU5000/10",code:"XU5000/10"}]},

  {deviceType:"dikey-supurge",brand:"dyson",familySlug:"kablosuz-dikey-supurge-modelleri",familyName:"Kablosuz Dikey Süpürge Modelleri",marketSourceUrl:STICK,catalogBasis:"Akakçe pazar keşfi + Dyson Türkiye ürün sahip/destek sayfaları",productUrl:"https://www.dyson.com.tr/products/vacuum-cleaners/cordless",supportUrl:"https://www.dyson.com.tr/destek",manualUrl:"https://www.dyson.com.tr/destek",softwareUrl:"https://www.dyson.com.tr/mydyson",models:["V16 Piston Animal","V16 Piston Animal Submarine","V15 Detect Absolute","V15s Detect Submarine","V12 Detect Slim Absolute","V12s Detect Slim Submarine","V10 Absolute Cyclone","V8 Cyclone"]},
  {deviceType:"dikey-supurge",brand:"philips",familySlug:"kablosuz-dikey-supurge-modelleri",familyName:"Kablosuz Dikey Süpürge Modelleri",marketSourceUrl:STICK,catalogBasis:"Akakçe pazar keşfi + Philips Türkiye model destek sayfaları",productUrl:"https://www.philips.com.tr/c-m-ho/elektrikli-supurgeler/kablosuz-elektrikli-supurgeler",supportUrl:"https://www.philips.com.tr/c-w/support-home.html",manualUrl:"https://www.philips.com.tr/c-w/support-home.html",models:[
    {name:"6000 Serisi XC6456/10",code:"XC6456/10"},{name:"6000 Serisi XC6452/10",code:"XC6452/10"},{name:"6000 Serisi XC6453/00",code:"XC6453/00"},
    {name:"7000 Serisi Aqua XC7057/01",code:"XC7057/01",productUrl:"https://www.philips.com.tr/c-p/XC7057_01/7000-serisi-kablosuz-elektrikli-suepuerge-aqua",manualUrl:"https://www.philips.com.tr/c-p/XC7057_01/7000-serisi-kablosuz-elektrikli-suepuerge-aqua/destek"},
    {name:"7000 Serisi Aqua XC7053/01",code:"XC7053/01"},{name:"8000 Serisi Aqua Plus XC8053/01",code:"XC8053/01"},{name:"AquaTrio 9000 Serisi XW9463/11",code:"XW9463/11"},{name:"AquaTrio 7000 Serisi XW7263/11",code:"XW7263/11"}
  ]},
  {deviceType:"dikey-supurge",brand:"bosch",familySlug:"unlimited",familyName:"Unlimited",familyKind:"official-family",marketSourceUrl:STICK,catalogBasis:"Akakçe pazar keşfi + Bosch Türkiye ürün/kılavuz sayfaları",productUrl:"https://www.bosch-home.com.tr/tr/category/elektrikli-supurgeler/sarjli-dikey-supurgeler",supportUrl:"https://www.bosch-home.com.tr/musteri-hizmetleri",manualUrl:"https://www.bosch-home.com.tr/musteri-hizmetleri/kullanim-kilavuzlari",models:[{name:"Unlimited 7 BBS711TR",code:"BBS711TR",productUrl:"https://www.bosch-home.com.tr/tr/product/elektrikli-supurgeler/sarjli-dikey-supurgeler/unlimited/unlimited-7/BBS711TR",manualUrl:"https://www.bosch-home.com.tr/tr/product/elektrikli-supurgeler/sarjli-dikey-supurgeler/unlimited/unlimited-7/BBS711TR"},{name:"Unlimited 7 BBS712XTR",code:"BBS712XTR"},{name:"Unlimited 10 BCS1041WAC",code:"BCS1041WAC"}]},
  {deviceType:"dikey-supurge",brand:"samsung",familySlug:"jet",familyName:"Jet",familyKind:"official-family",marketSourceUrl:STICK,catalogBasis:"Akakçe pazar keşfi + Samsung Türkiye model destek/kılavuz sayfaları",productUrl:"https://www.samsung.com/tr/vacuum-cleaners/stick/",supportUrl:"https://www.samsung.com/tr/support/",manualUrl:"https://www.samsung.com/tr/support/user-manuals-and-guide/",models:[{name:"Bespoke AI Jet Ultra Elite Extra VS90F40DAK/TR",code:"VS90F40DAK/TR",supportUrl:"https://www.samsung.com/tr/support/model/VS90F40DAK/TR/",manualUrl:"https://www.samsung.com/tr/support/model/VS90F40DAK/TR/"},{name:"Jet 60 Turbo VS15A6031R4/TR",code:"VS15A6031R4/TR",supportUrl:"https://www.samsung.com/tr/support/model/VS15A6031R4/TR/",manualUrl:"https://www.samsung.com/tr/support/model/VS15A6031R4/TR/"},{name:"Jet 75E VS20B75ACR5/TR",code:"VS20B75ACR5/TR",supportUrl:"https://www.samsung.com/tr/support/model/VS20B75ACR5/TR/",manualUrl:"https://www.samsung.com/tr/support/model/VS20B75ACR5/TR/"}]},
  {deviceType:"dikey-supurge",brand:"dreame",familySlug:"dikey-supurge-modelleri",familyName:"Dikey Süpürge Modelleri",marketSourceUrl:STICK,catalogBasis:"Akakçe pazar keşfi + Dreame Türkiye ürün destek/kılavuz merkezi",productUrl:"https://dreametech.com.tr/collections/dikey-supurge",supportUrl:"https://dreametech.com.tr/pages/product-support",manualUrl:"https://dreametech.com.tr/pages/kullanici-kilavuzu",models:["H15 Mix","Z30","R20"]},
  {deviceType:"dikey-supurge",brand:"shark",familySlug:"sarjli-dikey-supurge-modelleri",familyName:"Şarjlı Dikey Süpürge Modelleri",marketSourceUrl:STICK,catalogBasis:"Akakçe pazar keşfi + SharkNinja Türkiye ürün ve destek sayfaları",productUrl:"https://www.sharkninja.com.tr/collections/shark",supportUrl:"https://www.sharkninja.com.tr/pages/destek",manualUrl:"https://www.sharkninja.com.tr/pages/destek",models:["PowerDetect Clean & Empty","PowerPro Turbo","Detect Pro"]},
  {deviceType:"dikey-supurge",brand:"roborock",familySlug:"islak-kuru-dikey-supurge-modelleri",familyName:"Islak-Kuru Dikey Süpürge Modelleri",marketSourceUrl:STICK,catalogBasis:"Akakçe pazar keşfi + Roborock resmî ürün/destek",productUrl:"https://tr.roborock.com/collections/wet-dry-vacuum",supportUrl:"https://help.roborock.com/",manualUrl:"https://support.roborock.com/",models:["F25 Ultra","F25 ACE"]},

  {deviceType:"kahve-makinesi",brand:"philips",familySlug:"tam-otomatik-espresso",familyName:"Tam Otomatik Espresso Makineleri",marketSourceUrl:ESPRESSO,catalogBasis:"Akakçe espresso envanteri + Philips Türkiye ürün/destek sayfaları",productUrl:"https://www.philips.com.tr/c-m-ho/kahve-makineleri/tam-otomatik-espresso-makineleri",supportUrl:"https://www.philips.com.tr/c-w/support-home.html",manualUrl:"https://www.philips.com.tr/c-w/support-home.html",models:[{name:"3300 Serisi EP3341/50",code:"EP3341/50"},{name:"2300 Serisi LatteGo EP2331/10",code:"EP2331/10"},{name:"5500 Serisi LatteGo EP5544/80",code:"EP5544/80"},{name:"5500 Serisi LatteGo EP5547/90",code:"EP5547/90",productUrl:"https://www.philips.com.tr/c-p/EP5547_90/5500-serisi-tam-otomatik-espresso-makinesi",manualUrl:"https://www.philips.com.tr/c-p/EP5547_90/5500-serisi-tam-otomatik-espresso-makinesi/destek"},{name:"3200 Serisi LatteGo EP3246/70",code:"EP3246/70"},{name:"4400 Serisi LatteGo EP4446/70",code:"EP4446/70"},{name:"2200 Serisi EP2220/10",code:"EP2220/10"}]},
  {deviceType:"kahve-makinesi",brand:"philips",familySlug:"filtre-kahve-makineleri",familyName:"Filtre Kahve Makineleri",marketSourceUrl:FILTER,catalogBasis:"Akakçe filtre kahve envanteri + Philips Türkiye ürün/destek",productUrl:"https://www.philips.com.tr/c-m-ho/kahve-makineleri/filtre-kahve-makineleri",supportUrl:"https://www.philips.com.tr/c-w/support-home.html",manualUrl:"https://www.philips.com.tr/c-w/support-home.html",models:[{name:"Daily Collection HD7461/20",code:"HD7461/20"},{name:"Daily Collection HD7462/20",code:"HD7462/20"},{name:"Daily Collection HD7459/20",code:"HD7459/20"},{name:"Metal Therm HD7546/20",code:"HD7546/20"},{name:"Essentials Collection HD7430/90",code:"HD7430/90"}]},
  {deviceType:"kahve-makinesi",brand:"delonghi",familySlug:"espresso-makineleri",familyName:"Espresso Makineleri",marketSourceUrl:ESPRESSO,catalogBasis:"Akakçe espresso envanteri + De'Longhi resmî ürün/kılavuz sayfaları",productUrl:"https://www.delonghi.com/tr-tr/kahve/kahve-makineleri/c/coffee_makers",supportUrl:"https://www.delonghi.com/tr-tr/contact-us",manualUrl:"https://www.delonghi.com/tr-tr/manuals",models:[{name:"Magnifica Start ECAM220.60.B",code:"ECAM220.60.B",manualUrl:"https://www.delonghi.com/medias/ECAM22060B-274219?context=bWFzdGVyfGRhbV9tYW51YWxzfDkzMzk0OTh8YXBwbGljYXRpb24vcGRm"},{name:"Magnifica Evo ECAM290.21.B",code:"ECAM290.21.B"},{name:"Magnifica Evo ECAM290.61.B",code:"ECAM290.61.B"},{name:"Magnifica Evo ECAM290.81.TB",code:"ECAM290.81.TB"},{name:"Magnifica Plus ECAM320.70.TB",code:"ECAM320.70.TB"},{name:"Rivelia EXAM440.55",code:"EXAM440.55"},{name:"Eletta Explore ECAM450.86.T",code:"ECAM450.86.T"},{name:"Dedica EC685",code:"EC685"}]},
  {deviceType:"kahve-makinesi",brand:"nespresso",familySlug:"kapsul-kahve-makineleri",familyName:"Kapsül Kahve Makineleri",marketSourceUrl:CAPSULE,catalogBasis:"Akakçe kapsül kahve envanteri + Nespresso Türkiye Makine Yardımı",productUrl:"https://www.nespresso.com/tr/tr/order/machines",supportUrl:"https://www.nespresso.com/tr/tr/machine-assistance",manualUrl:"https://www.nespresso.com/tr/tr/machine-assistance",models:["Essenza Mini","Gran Lattissima","Creatista Plus","Creatista Pro","Atelier","Lattissima One","Vertuo Next","Pixie","Citiz Platinum","Inissia"]},
  {deviceType:"kahve-makinesi",brand:"tchibo",familySlug:"cafissimo",familyName:"Cafissimo",familyKind:"official-family",marketSourceUrl:CAPSULE,catalogBasis:"Akakçe kapsül kahve envanteri + Tchibo Türkiye servis/destek",productUrl:"https://www.tchibo.com.tr/cafissimo-c400060628.html",supportUrl:"https://www.tchibo.com.tr/service-destek-s400120697.html",manualUrl:"https://www.tchibo.com.tr/service-destek-s400120697.html",models:["Cafissimo Pure Plus","Cafissimo Pure","Cafissimo Picco"]},
  {deviceType:"kahve-makinesi",brand:"arcelik",familySlug:"kahve-makinesi-modelleri",familyName:"Kahve Makinesi Modelleri",marketSourceUrl:ESPRESSO,catalogBasis:"Akakçe kahve envanteri + Arçelik Türkiye ürün/kılavuz sayfaları",productUrl:"https://www.arcelik.com.tr/kahve-makinesi",supportUrl:"https://www.arcelik.com.tr/destek",manualUrl:"https://www.arcelik.com.tr/destek/kullanim-kilavuzu",models:[{name:"Telvesso TEM 9690",code:"TEM 9690"},{name:"Resital FK 6910",code:"FK 6910",manualUrl:"https://www.arcelik.com.tr/medias/tr-TR-8810801100-202012290033719-User-Manual-File-Long-tr-TR.pdf?attachment=true"},{name:"FK 6310 S",code:"FK 6310 S"},{name:"FK 9314 I",code:"FK 9314 I"}]},
  {deviceType:"kahve-makinesi",brand:"beko",familySlug:"kahve-makinesi-modelleri",familyName:"Kahve Makinesi Modelleri",marketSourceUrl:ESPRESSO,catalogBasis:"Akakçe kahve envanteri + Beko Türkiye ürün/kılavuz sayfaları",productUrl:"https://www.beko.com.tr/kahve-makinesi",supportUrl:"https://www.beko.com.tr/destek",manualUrl:"https://www.beko.com.tr/destek/kullanim-kilavuzu",models:[{name:"Caffe Experto Deluxe TEM 8690",code:"TEM 8690"},{name:"CaffeExperto CEG 7304 X",code:"CEG 7304 X"}]},
  {deviceType:"kahve-makinesi",brand:"grundig",familySlug:"delisia-coffee",familyName:"Delisia Coffee",familyKind:"official-family",marketSourceUrl:ESPRESSO,catalogBasis:"Akakçe espresso envanteri + Grundig Türkiye ürün/destek",productUrl:"https://www.grundig.com.tr/kahve-makinesi",supportUrl:"https://www.grundig.com.tr/destek",manualUrl:"https://www.grundig.com.tr/destek",models:[{name:"Delisia Coffee KSM 4330",code:"KSM 4330"},{name:"Delisia Coffee KSM 5330",code:"KSM 5330"},{name:"Delisia KVA 8230",code:"KVA 8230"},{name:"KM 7340 Filtre Kahve Makinesi",code:"KM 7340"}]},
  {deviceType:"kahve-makinesi",brand:"arzum",familySlug:"kahve-makinesi-modelleri",familyName:"Kahve Makinesi Modelleri",marketSourceUrl:FILTER,catalogBasis:"Akakçe kahve envanteri + Arzum resmî ürün/kılavuz",productUrl:"https://www.arzum.com.tr/kahve-makineleri",supportUrl:"https://www.arzum.com.tr/musteri-destek",manualUrl:"https://www.arzum.com.tr/kullanma-kilavuzlari",models:[{name:"Brewtime Delux AR3081",code:"AR3081"},{name:"Brew'n Take AR3058",code:"AR3058"},{name:"Intenso OK0045",code:"OK0045"}]},
  {deviceType:"kahve-makinesi",brand:"vestel",familySlug:"kahve-makinesi-modelleri",familyName:"Kahve Makinesi Modelleri",marketSourceUrl:FILTER,catalogBasis:"Akakçe kahve envanteri + Vestel Türkiye ürün/kılavuz",productUrl:"https://www.vestel.com.tr/kahve-makineleri-c-502",supportUrl:"https://www.vestel.com.tr/destek",manualUrl:"https://www.vestel.com.tr/destek/kullanim-kilavuzlari",models:["Brew 50 DX","Brew 50 Retro","Keyif 30","Taze Öğütücülü","Sefa K3000"]},
  {deviceType:"kahve-makinesi",brand:"ninja",familySlug:"kahve-makinesi-modelleri",familyName:"Kahve Makinesi Modelleri",marketSourceUrl:ESPRESSO,catalogBasis:"Akakçe kahve envanteri + SharkNinja Türkiye resmî ürün/destek",productUrl:"https://www.sharkninja.com.tr/collections/kahve-makineleri",supportUrl:"https://www.sharkninja.com.tr/pages/destek",manualUrl:"https://www.sharkninja.com.tr/pages/destek",models:["Luxe Café Premier","Prestige DualBrew"]}
];

const built=definitions.map(defineCatalog);
export const homeFamilies=built.map(x=>x.family);
export const homeModels=built.flatMap(x=>x.models);
