// Akakçe yalnızca Türkiye pazarında fiilen listelenen envanteri keşfetmek için kullanılır.
// Ürün desteği, kılavuz, yazılım veya yetkili servis kaynağı olarak kullanılmaz.
export const marketInventory=[
  {deviceType:"robot-supurge",sourceUrl:"https://www.akakce.com/robot-supurge.html",observedListings:1119,observedAt:"2026-08-26",note:"Renk ve paket varyantları ayrı ticari kayıt oluşturabilir."},
  {deviceType:"dikey-supurge",sourceUrl:"https://www.akakce.com/dikey-supurge.html",observedListings:1855,observedAt:"2026-08-26",subgroups:["Kablosuz dikey süpürge","Islak-kuru dikey süpürge"]},
  {deviceType:"kahve-makinesi",sourceUrl:"https://www.akakce.com/kahve-makinesi.html",observedListings:null,observedAt:"2026-08-26",subgroups:[{name:"Espresso makinesi",sourceUrl:"https://www.akakce.com/espresso-makinesi.html",observedListings:922},{name:"Filtre kahve makinesi",sourceUrl:"https://www.akakce.com/filtre-kahve-makinesi.html",observedListings:1027},{name:"Kapsül kahve makinesi",sourceUrl:"https://www.akakce.com/kapsul-kahve-makinesi.html",observedListings:175},{name:"Türk kahve makinesi",sourceUrl:"https://www.akakce.com/turk-kahve-makinesi.html",observedListings:1021}]},
  {deviceType:"dizustu-bilgisayar",sourceUrl:"https://www.akakce.com/laptop-notebook.html",observedListings:195263,observedAt:"2026-08-26",note:"Bellek, depolama, işletim sistemi ve renk SKU'ları ayrı ticari kayıt olabilir."},
  {deviceType:"masaustu-bilgisayar",sourceUrl:"https://www.akakce.com/bilgisayar-masaustu.html",observedListings:127248,observedAt:"2026-08-26",subgroups:["Marka masaüstü bilgisayar","Masaüstü oyun bilgisayarı"],note:"Toplama sistem ve bileşen kombinasyonları toplamı büyütür; katalog üretici model koduna göre tekilleştirilir."},
  {deviceType:"televizyon",sourceUrl:"https://www.akakce.com/televizyon.html",observedListings:1704,observedBrands:81,observedAt:"2026-08-26",note:"Ekran boyu aynı seri içinde ayrı tam model kodudur."},
  {deviceType:"yazici",sourceUrl:"https://www.akakce.com/yazici.html",observedListings:null,observedAt:"2026-08-26",subgroups:[{name:"Lazer yazıcı",sourceUrl:"https://www.akakce.com/lazer-yazici.html",observedListings:530},{name:"Mürekkep püskürtmeli yazıcı",sourceUrl:"https://www.akakce.com/murekkep-puskurtmeli-yazici.html",observedListings:294}],note:"3D, barkod, kart ve endüstriyel yazıcılar bu tüketici sorun giderme kapsamından ayrı tutulur."},
  {deviceType:"klima",sourceUrl:"https://www.akakce.com/klima.html",observedListings:2925,observedBrands:107,observedAt:"2026-08-26",subgroups:["Duvar tipi split klima","Mobil klima"]},
  {deviceType:"elektrikli-scooter",sourceUrl:"https://www.akakce.com/elektrikli-scooter.html",observedListings:221,observedAt:"2026-08-26",note:"Renk ve kasklı paket varyantları aynı model altında tekilleştirilir."},
  {deviceType:"kedi-kopek-tiras-makinesi",sourceUrl:"https://www.akakce.com/kedi-kopek-tiras-makinesi.html",observedListings:265,observedBrands:37,observedAt:"2026-09-04",note:"Kategori yedek bıçak, aksesuar, paket/renk varyantı ve yanlış sınıflanan insan tıraş makineleri de içerebilir. Public katalog yalnız tam cihaz + resmî model/kullanım-bakım kaynağı doğrulanan kayıtları tekilleştirir."},
  {deviceType:"elektrikli-bisiklet",sourceUrl:"https://www.akakce.com/elektrikli-bisiklet.html",observedListings:587,observedBrands:42,observedAt:"2026-09-05",note:"Akakçe sayısı renk/SKU değişimleriyle dalgalanabilir. Resmî üretici sınıflandırması e-bike ile moped/motosiklet ayrımında önceliklidir; VSM bu nedenle e-bike kataloğuna alınmaz."}
];

export const marketInventoryByDevice=new Map(marketInventory.map(x=>[x.deviceType,x]));
