import { deviceTypes,brands,families,models,issues,pathForDeviceType,pathForBrand,pathForFamily,pathForModel,pathForIssue,supportLinksForBrand } from "./catalog.js";
import { esc,ext,page,crumb,tree,SITE_ORIGIN } from "./ui-base.js";

function brandSupport(b){
  const links=supportLinksForBrand(b).map(([label,url])=>`<div class="source">${ext(url,label)}</div>`).join("");
  return `<div class="card"><span class="kicker">Marka destek merkezi</span><h3>Resmî kaynaklar</h3>${links||'<p>Doğrulanmış resmî kaynak bağlantısı henüz yayımlanmadı.</p>'}<p><b>Servis kuralı:</b> ${esc(b.serviceSummary||"Yetkili servis adı yalnızca markanın resmî kaynağında doğrulanır.")}</p></div>`;
}

export function renderHome(){
  const cards=deviceTypes.map(d=>`<a class="card cardLink" href="${pathForDeviceType(d)}"><span class="kicker">Cihaz türü</span><h3>${esc(d.name)}</h3><p>${esc(d.description)}</p><b>Markaları ve destek kaynaklarını aç →</b></a>`).join("");
  return page("Arıza Nerede? | Cihaz arızası, hata kodu, kılavuz ve resmî servis","Cihaz türünü, markayı, seriyi ve modeli seç; hata kodunun anlamını, güvenli çözümü, kılavuzu, sürücü/yazılım kaynağını ve resmî servisi bul.",`${SITE_ORIGIN}/`,`<div class="shell"><section class="hero"><span class="eyebrow">Teşhis ağacı + resmî kaynak</span><h1>Cihazın ne söylüyor? Arızanın izini adım adım bul.</h1><p>Marka, model, hata kodu, belirti, sürücü veya kılavuzdaki bir ibareyi ara. Resmî kaynak öncelikli, güvenli kullanıcı müdahalesi sınırları belirlenmiş cevap merkezi.</p><form class="search" action="/ara"><input name="q" maxlength="140" placeholder="Örn: Xiaomi Scooter hata 14 ne demek?"><button class="btn">Ara</button></form></section><section class="section" id="cihazlar"><h2>Cihaz türünü seç</h2><div class="grid">${cards}</div></section></div>`)
}

export function renderDeviceType(d){
  const rows=brands.filter(b=>b.deviceTypes.includes(d.slug)).sort((a,b)=>a.name.localeCompare(b.name,"tr")).map(b=>`<a class="card cardLink" href="${pathForBrand(d.slug,b.slug)}"><span class="kicker">${esc(d.name)}</span><h3>${esc(b.name)}</h3><p>Resmî destek, kılavuz, yazılım/sürücü ve marka doğrulamalı servis kaynağı.</p></a>`).join("");
  return page(`${d.name} arıza kodları, markalar ve destek | Arıza Nerede?`,`${d.name} markaları, hata kodları, kılavuz, sürücü/yazılım ve resmî servis kaynakları.`,`${SITE_ORIGIN}${pathForDeviceType(d)}`,`<div class="shell">${crumb([{label:"Ana sayfa",url:"/"},{label:d.name}])}<section class="detail"><span class="eyebrow">Cihaz türü</span><h1 class="title">${esc(d.name)}</h1><p class="lead">Markayı seç. Seri ve tam model ağacı yalnızca katalog doğrulaması tamamlanan markalarda yayımlanır.</p><div class="grid">${rows||'<div class="empty">Bu cihaz türü için doğrulanmış marka kaydı hazırlanıyor.</div>'}</div></section></div>`)
}

export function renderBrand(d,b){
  const familyRows=families.filter(f=>f.deviceType===d.slug&&f.brand===b.slug).map(f=>`<a class="card cardLink" href="${pathForFamily(f)}"><span class="kicker">Seri / model ailesi</span><h3>${esc(f.name)}</h3><p>Tam cihaz modellerini aç.</p></a>`).join("");
  const treeBlock=familyRows?`<section style="margin-top:22px"><h2>Doğrulanmış seri / model aileleri</h2><div class="grid">${familyRows}</div></section>`:`<div class="empty" style="margin-top:18px"><b>Seri/model ağacı henüz yayımlanmadı.</b><br>Bu bir eksik katalog değildir: Türkiye'de satılan seri ve tam model listesi marka kaynaklarıyla tamamlanmadan kısmi listeyi indekslemiyoruz. Bu sırada resmî destek, kılavuz, yazılım ve servis bağlantıları kullanılabilir.</div>`;
  return page(`${b.name} ${d.name} destek, kılavuz, servis ve modeller | Arıza Nerede?`,`${b.name} ${d.name} resmî destek, kılavuz, sürücü/yazılım, yetkili servis ve doğrulanmış model ağacı.`,`${SITE_ORIGIN}${pathForBrand(d.slug,b.slug)}`,`<div class="shell">${crumb([{label:"Ana sayfa",url:"/"},{label:d.name,url:pathForDeviceType(d)},{label:b.name}])}<section class="detail"><span class="eyebrow">${esc(d.name)}</span><h1 class="title">${esc(b.name)}</h1><div class="cols"><article><p class="lead">Öncelik markanın kendi teknik verisidir. Yetkili servis olarak yalnızca marka tarafından doğrulanan kanal gösterilir.</p>${treeBlock}</article><aside class="side">${brandSupport(b)}<div class="card" style="margin-top:14px"><span class="kicker">Servis veya garanti sorunu</span><p>Servis kaydı, teslim belgesi, garanti veya onarım uyuşmazlığında haklarınızı ayrı rehberden kontrol edin.</p><a class="btn alt" href="/servis-garanti-haklari/">Servis ve tüketici hakları →</a></div></aside></div></section></div>`)
}

export function renderFamily(d,b,f){
  const rows=models.filter(m=>m.deviceType===d.slug&&m.brand===b.slug&&m.family===f.slug).map(m=>`<a class="card cardLink" href="${pathForModel(m)}"><span class="kicker">Tam cihaz modeli</span><h3>${esc(b.name)} ${esc(m.name)}</h3><p>Arıza kodları, belirtiler, kılavuz, yazılım ve servis.</p></a>`).join("");
  return page(`${b.name} ${f.name} modelleri | Arıza Nerede?`,`${b.name} ${f.name} tam model listesi ve doğrulanmış arıza kaynakları.`,`${SITE_ORIGIN}${pathForFamily(f)}`,`<div class="shell">${crumb([{label:"Ana sayfa",url:"/"},{label:d.name,url:pathForDeviceType(d)},{label:b.name,url:pathForBrand(d.slug,b.slug)},{label:f.name}])}<section class="detail"><span class="eyebrow">Seri / model ailesi</span><h1 class="title">${esc(b.name)} ${esc(f.name)}</h1><div class="grid">${rows||'<div class="empty">Bu seri için eksiksiz tam model listesi doğrulanmadan yayın yapılmıyor.</div>'}</div></section></div>`)
}

export function renderModel(d,b,f,m){
  const rows=issues.filter(i=>i.model===m.slug&&i.brand===b.slug&&i.deviceType===d.slug).map(i=>`<a class="result" href="${pathForIssue(i)}"><small>${esc(i.code)}</small><br><strong>${esc(i.title)}</strong><p>${esc(i.short)}</p></a>`).join("");
  const soft=m.softwareResources?.length?m.softwareResources.map(r=>`<div class="source"><small>Yazılım / firmware / uygulama</small>${ext(r.url,r.label)}<p>${esc(r.note)}</p></div>`).join(""):`<div class="source"><small>Yazılım</small>Doğrulanmış ayrı bir indirme kaynağı bulunmuyor.</div>`;
  return page(`${b.name} ${m.name} arıza kodları, kılavuz ve destek | Arıza Nerede?`,`${b.name} ${m.name} hata kodları, sorunlar, kullanıcı kılavuzu, resmî destek ve yazılım kaynağı.`,`${SITE_ORIGIN}${pathForModel(m)}`,`<div class="shell">${crumb([{label:"Ana sayfa",url:"/"},{label:d.name,url:pathForDeviceType(d)},{label:b.name,url:pathForBrand(d.slug,b.slug)},{label:f.name,url:pathForFamily(f)},{label:m.name}])}<section class="detail"><span class="eyebrow">Tam cihaz modeli</span><h1 class="title">${esc(b.name)} ${esc(m.name)}</h1>${tree([{label:d.name,url:pathForDeviceType(d)},{label:b.name,url:pathForBrand(d.slug,b.slug)},{label:f.name,url:pathForFamily(f)},{label:m.name}])}<div class="cols"><article><h2>Arıza kodları ve belirtiler</h2><div class="results">${rows||'<div class="empty">Bu model için doğrulanmış sorun kaydı hazırlanıyor.</div>'}</div></article><aside class="side"><div class="card"><span class="kicker">Resmî model kaynakları</span><div class="source">${ext(m.supportUrl,"Resmî destek")}</div><div class="source">${ext(m.manualUrl,"Kılavuz / belgeler")}</div>${soft}</div></aside></div></section></div>`)
}
