import { legalResources, escalationRoutes, SERBIS_URL, SITE_ORIGIN } from "./catalog.js";
import { esc,ext,page,crumb } from "./ui-base.js";

export function renderServiceRights(){
  const legal=legalResources.map(r=>`<div class="source"><small>${esc(r.authority)}</small>${ext(r.url,r.label)}</div>`).join("");
  const routes=escalationRoutes.map(r=>`<a class="route" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.title)} ↗</a>`).join("");
  return page(
    "Yetkili servis, garanti ve tüketici hakları | Arıza Nerede?",
    "Cihazı servise verirken belge, veri yedekleme, yetkili servis doğrulaması, garanti ve çözülemeyen servis uyuşmazlıklarında izlenecek yol.",
    `${SITE_ORIGIN}/servis-garanti-haklari/`,
    `<div class="shell">${crumb([{label:"Ana sayfa",url:"/"},{label:"Servis ve garanti hakları"}])}<section class="detail"><span class="eyebrow">Servis süreci</span><h1 class="title">Yetkili servise gitmeden önce ve sonra ne yapmalı?</h1><p class="lead">Arıza teknik bir sorun olmaktan çıkıp servis sürecine geçtiğinde, doğru servis kadar kayıt ve belge de önemlidir. Buradaki yönlendirmeler resmî Ticaret Bakanlığı kaynaklarına dayanır.</p><div class="cols"><article><div class="qa"><div class="card"><span class="kicker">1 · Servisi doğrula</span><h2>Marka kaynağı önce gelir</h2><p>Arıza Nerede yalnızca markanın kendi Türkiye sayfasında veya resmî destek kanalında doğruladığı servisleri isimle gösterir. İkinci kontrol için SERBİS kullanılır.</p><div class="actions">${ext(SERBIS_URL,"SERBİS'te yetkili servis sorgula","btn alt")}</div></div><div class="card"><span class="kicker">2 · Teslimden önce</span><h2>Belge ve veriyi hazırla</h2><ul><li>Fatura/garanti belgesi, model ve seri numarasını kaydet.</li><li>Arızayı fotoğraf, video veya hata koduyla mümkün olduğunca belgele.</li><li>Bilgisayar, telefon, TV ve benzeri veri tutan cihazlarda mümkünse yedek al ve hesaplardan çıkış yap.</li><li>Servise teslim edilen aksesuarları teslim belgesine yazdır.</li></ul></div><div class="card"><span class="kicker">3 · Teslim belgesi</span><h2>Arızayı ve talebini yazdır</h2><p>Ticaret Bakanlığı, servis istasyonlarının teslim aldıkları arızalı mallar için teslim belgesi düzenlemesi gerektiğini belirtiyor. Ücretsiz onarım, değişim veya başka bir seçimlik hakkı talep ediyorsan talebin belgede açık olması ispat açısından önemlidir.</p></div><div class="card"><span class="kicker">4 · Süreyi ürün bazında kontrol et</span><h2>Tek bir süreyi bütün cihazlara uygulama</h2><p>Azami tamir süresi ürün grubuna göre Satış Sonrası Hizmetler Yönetmeliği ekinde değişebilir. Bu nedenle Arıza Nerede sabit bir gün sayısını bütün cihazlara kopyalamaz; işlem anında ürün grubunun güncel resmî kaynağı kontrol edilir.</p></div><div class="card"><span class="kicker">5 · Sorun çözülmezse</span><h2>Teknik çözümden tüketici hakkına geç</h2><p>Servis ürünü onarmıyor, garanti kapsamı reddediliyor, ürün tekrarlayan şekilde arızalanıyor veya satıcı seçimlik hakkı kabul etmiyorsa teknik rehberin sınırı biter. Bundan sonra uygun başvuru rotası NereyeBaşvurulur üzerinden izlenebilir.</p><div class="routes">${routes}</div></div></div></article><aside class="side"><div class="card"><span class="kicker">Resmî hukuk kaynakları</span><h3>Ticaret Bakanlığı</h3>${legal}</div><div class="card" style="margin-top:14px"><span class="kicker">Önemli ayrım</span><p>Arıza Nerede hukuki temsil veya teknik servis değildir. Amacı doğru resmî kaynağı, güvenli kullanıcı adımını ve profesyonel servise geçiş eşiğini görünür kılmaktır.</p></div></aside></div></section></div>`
  );
}
